CREATE TABLE Curso (
CodC VARCHAR(3) PRIMARY KEY, --MUDAR VARCHAR PARA 2
NomeC VARCHAR(15) NOT NULL,
DuracaoC INT NOT NULL,
MensC INT NOT NULL
)

CREATE TABLE Professor(
CodP VARCHAR(2) PRIMARY KEY,
NomeP VARCHAR (15) NOT NULL,
CidadeP VARCHAR (15) NOT NULL,
TituloP VARCHAR (15) NOT NULL
)

CREATE TABLE Disciplina(
CodP VARCHAR(2) PRIMARY KEY,
NomeD VARCHAR(15) NOT NULL,
CargaD INT NOT NULL,
AreaD VARCHAR(15),
PreReqD VARCHAR(15)
)

EXEC sp_rename 'Disciplina.CodP','CodD'

SELECT *
FROM Disciplina

CREATE TABLE Grade(
CodC VARCHAR(3) FOREIGN KEY REFERENCES Curso(CodC),
CodD VARCHAR(2) FOREIGN KEY REFERENCES Disciplina(CodD),
CodP VARCHAR(2) FOREIGN KEY REFERENCES Professor(CodP),
Sala INT NOT NULL
)

